version: '3'
services:
  ink_backend_admin:
    networks:
      - ink_default

    image: docker.io/$DOCKER_USERNAME/$IMAGE:$VERSION
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.was2.rule=Host(`admin.hkpark.net`)"
      - "traefik.http.routers.was2.entrypoints=websecure"
      - "traefik.http.routers.was2.tls.certresolver=myresolver"
    container_name: ink_backend_admin
    restart: always
    ports:
      - "8001:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - CLOUD_AWS_CREDENTIALS_ACCESS_KEY=$CLOUD_AWS_CREDENTIALS_ACCESS_KEY
      - CLOUD_AWS_CREDENTIALS_SECRET_KEY=$CLOUD_AWS_CREDENTIALS_SECRET_KEY
      - AWS_ACCESS_KEY=$CLOUD_AWS_CREDENTIALS_ACCESS_KEY
      - AWS_SECRET_KEY=$CLOUD_AWS_CREDENTIALS_SECRET_KEY

networks:
  ink_default:
    external: true