version: '3'
services:
  ink_backend_api:
    image: docker.io/$DOCKER_USERNAME/$IMAGE:$VERSION
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.was1.rule=Host(`dev.hkpark.net`)"
      - "traefik.http.routers.was1.entrypoints=web"
    container_name: ink_backend_api
    restart: always
    ports:
      - "8000:8080"
    environment:
      - SPRING_PROFILES_ACTIVE="dev"
      - CLOUD_AWS_CREDENTIALS_ACCESS_KEY=$CLOUD_AWS_CREDENTIALS_ACCESS_KEY
      - CLOUD_AWS_CREDENTIALS_SECRET_KEY=$CLOUD_AWS_CREDENTIALS_SECRET_KEY
      - AWS_ACCESS_KEY=$CLOUD_AWS_CREDENTIALS_ACCESS_KEY
      - AWS_SECRET_KEY=$CLOUD_AWS_CREDENTIALS_SECRET_KEY